rdkcentral/meta-rdk-video

- recipes-extended/networkmgr-plugin/networkmanager-plugin_git.bb
Reason for change: Integrate unit test framework
Test Procedure: Invoked unit test on every PR
> RDK-56730: Unit test framework for routerDiscovery

- recipes-extended/networkmgr-plugin/networkmanager-plugin_git.bb
Reason for change: Integrate unit test framework
Test Procedure: Invoked unit test on every PR
> RDK-56730: Unit test framework for routerDiscovery (#11)

- recipes-extended/entservices/entservices-casting.bb
- recipes-extended/wpe-framework/rdkservices-apis_1.0.bb
- recipes-extended/xdial/xdial.bb
RDK-55044: Implement DIAL requirement to use on EU product
Signed-off-by: yuvaramachandran_gurusamy <yuvaramachandran_gurusamy@comcast.com>
> RDK-55044: Implement DIAL requirement to use on EU product

- recipes-extended/entservices/entservices-deviceanddisplay.bb
Reason for change: IDeviceOptimizeStateActivator interface for DisplaySettings - Realtek (for supporting allm)
Test Procedure: Build and verify
> RDK-56643:IDeviceOptimizeStateActivator interface for Thunder Interface

- recipes-extended/entservices/entservices-casting.bb
- recipes-extended/entservices/entservices-deviceanddisplay.bb
- recipes-extended/entservices/entservices-infra.bb
- recipes-extended/entservices/entservices-inputoutput.bb
- recipes-extended/entservices/entservices-peripherals.bb
- recipes-extended/iarmmgrs/iarmmgrs_git.bb
- recipes-extended/wpe-framework/rdkservices-apis_1.0.bb
- recipes-extended/wpe-framework/wpeframework-clientlibraries/r4.4/0001-PowerManagerClient-library-implementation.patch
- recipes-extended/wpe-framework/wpeframework/wpeframework.service.in
- recipes-thirdparty/tr69hostif/tr69hostif_git.bb
Reason for change: PowerManager PowerMode pre-change handling & restructure events
Test Procedure: Refer RDK-55706, RDK-56249
Risks: Medium
Signed-off-by:bp-skamat286 skamath@synamedia.com
> RDK-55706 PowerModePreChange & Connect retry handling

- recipes-extended/networkmgr-plugin/networkmanager-plugin_git.bb
* WPS operation time out updated
* WPS Wait updated
* Event posting added
* SSID restriction added
* GetConnectedSSID changed to return only when its valid/usable (ie IP address set) Test Procedure: Check the WPS funcitonality
Risks: Medium
> RDKEMW-1447, RDKEMW-2788, RDKEMW-2666  WPS - Screen is stuck Issue

- recipes-extended/networkmgr-plugin/networkmanager-plugin_git.bb
* WPS operation time out updated
* WPS Wait updated
* Event posting added
* SSID restriction added
* GetConnectedSSID changed to return only when its valid/usable (ie IP address set) Test Procedure: Check the WPS funcitonality
Risks: Medium
> RDKEMW-1447, RDKEMW-2788, RDKEMW-2666  WPS - Screen is stuck Issue (#51)

- recipes-extended/entservices/entservices-mediaanddrm.bb
- recipes-extended/entservices/include/texttospeech.inc
* RDKEMW-2503 : Config changes for EAA
Reason for change: change default voice
Risks: Low
* RDKEMW-2503 : Config changes for EAA
Reason for change: change default voice
Risks: Low
* RDKEMW-2503 : Config changes for EAA
Reason for change: update srcrev
Risks: Low
* RDKEMW-2503 : Config changes for EAA
Reason for change: config change & SRCREV update
Risks: Low
---------
> RDKEMW-2503 : Config changes for EAA (#18)

- recipes-extended/entservices/entservices-mediaanddrm.bb
Reason for change: Bug fix
Risks: Low
> RDKEMW-3169 : Fix VREX TTS2.0 VG not working in RDKE (#92)

- recipes-extended/sysint/sysint_git.bb
> RDKEMW-3268: Integrate Zram for RDK platforms to control to control swap feature 

- recipes-extended/cobalt/files/25/0001-Fix-NPBL-with-cast_codec_tests-config.patch
- recipes-extended/cobalt/files/25/0001-Include-RDK-platforms.patch
- recipes-extended/cobalt/larboard_revision.inc
- recipes-extended/cobalt/libloader-app_25.lts.stable.bb
- recipes-extended/cobalt/nplb_25.lts.stable.bb
- recipes-extended/thunderstartupservices/thunderstartupservices.bb
> Rebase Develop

- recipes-graphics/javascriptcore/javascriptcore_git.bb
Reason for change: Optimization of javascriptcode lib
Test Procedure: build should be successful.
Risks: low
Priority: P2
> RDKEMW-3572 : Observed increase in image size for RDKE Middleware  build

- conf/layer.conf
- recipes-extended/subtec-app/dvbsubdecoder/dvbsubdecoder.bb
- recipes-extended/subtec-app/subttxrend-app/files/config.ini
- recipes-extended/subtec-app/subttxrend-app/files/subttxrend-app.service
- recipes-extended/subtec-app/subttxrend-app/files/wait-for-subttxrend-socket.sh
- recipes-extended/subtec-app/subttxrend-app/subttxrend-app.bb
- recipes-extended/subtec-app/subttxrend-cc/subttxrend-cc.bb
- recipes-extended/subtec-app/subttxrend-common/subttxrend-common.bb
- recipes-extended/subtec-app/subttxrend-ctrl/subttxrend-ctrl.bb
- recipes-extended/subtec-app/subttxrend-dbus/subttxrend-dbus.bb
- recipes-extended/subtec-app/subttxrend-dvbsub/subttxrend-dvbsub.bb
- recipes-extended/subtec-app/subttxrend-gfx/subttxrend-gfx.bb
- recipes-extended/subtec-app/subttxrend-protocol/subttxrend-protocol.bb
- recipes-extended/subtec-app/subttxrend-scte/subttxrend-scte.bb
- recipes-extended/subtec-app/subttxrend-socksrc/subttxrend-socksrc.bb
- recipes-extended/subtec-app/subttxrend-ttml/files/006-subttxrend-ttml-hardcode-center-textalign.patch
- recipes-extended/subtec-app/subttxrend-ttml/subttxrend-ttml.bb
- recipes-extended/subtec-app/subttxrend-ttxt/subttxrend-ttxt.bb
- recipes-extended/subtec-app/subttxrend-webvtt/subttxrend-webvtt.bb
- recipes-extended/subtec-app/ttxdecoder/ttxdecoder.bb
* RDKEMW-3080: move subtec to meta-rdk-video
* RDKEMW-3080: move subtec to meta-rdk-video
* RDKEMW-3080: move subtec to meta-rdk-video
Signed-off-by: Tony Paul <Tony_Paul@comcast.com>
* RDKEMW-3080: move subtec to meta-rdk-video
Signed-off-by: Tony Paul <Tony_Paul@comcast.com>
* RDKEMW-3080:move subtec to meta-rdk-video
Signed-off-by: Tony Paul <Tony_Paul@comcast.com>
> RDKEMW-3080: move subtec to meta-rdk-video (#62)

- recipes-extended/cobalt/libloader-app_24.lts.stable.bb
- recipes-extended/cobalt/libloader-app_25.lts.stable.bb
Set rdkcentral URL
Test Procedure: Make local VM build
Risks: Low
> RDKEMW-3670: Local VM libloader-app fetch error

- recipes-extended/networkmgr-plugin/networkmanager-plugin_git.bb
Reason for change: Updated the networkmanager plugin version to 0.14.0
Risks: low
Priority: P1
> RDKEMW-2191 - GetPrimaryInterface is returning wrong value

- recipes-extended/entservices/entservices-deviceanddisplay.bb
RDKEMW-2808: RDKE/V User Settings Update Presentation language in Failure
Reason for change: RDKE/V User Settings Update Presentation language in Failure
Risks: NO
Priority: P1
> RDKEMW-2808: RDKE/V User Settings Update Presentation language in Failure

- recipes-extended/entservices/entservices-deviceanddisplay.bb
- recipes-extended/wpe-framework/rdkservices-apis_1.0.bb
Reason for change: Add COM-RPC support to Warehouse plugin 
Test Procedure: Test Warehouse - All APIs
Risks: Medium
Priority: P1
Signed-off-by:Dineshkumar P dinesh_kumar2@comcast.com
> RDKEMW-1024 Add COM-RPC support to Warehouse plugin

- recipes-extended/entservices/entservices-deviceanddisplay.bb
- recipes-extended/wpe-framework/rdkservices-apis_1.0.bb
Reason for change: Add COM-RPC support to Warehouse plugin Test Procedure: Test Warehouse - All APIs
Risks: Medium
Priority: P1
Signed-off-by:Dineshkumar P dinesh_kumar2@comcast.com
> RDKEMW-1024 Add COM-RPC support to Warehouse plugin (#254)

- recipes-extended/entservices/entservices-casting.bb
- recipes-extended/entservices/entservices-deviceanddisplay.bb
- recipes-extended/entservices/entservices-infra.bb
- recipes-extended/entservices/entservices-inputoutput.bb
- recipes-extended/entservices/entservices-peripherals.bb
- recipes-extended/wpe-framework/entservices-apis.bb
- recipes-extended/wpe-framework/wpeframework-clientlibraries/r4.4/0001-PowerManagerClient-library-implementation.patch
RDK-57093: PowerManager Interface methods and event APIs modified
Reason for changes: The Interface method return type and event APIs are modified as per API spec
Test procedure: Full stack build
Risk: Low
> RDK-57093: PowerManager Interface methods and event APIs modified

- recipes-extended/sysint/sysint_git.bb
Reason for change: Add fix for zram feature
Test Procedure: Build RDKE image
Risks: Low
Signed-off-by: Aravindan NC [nc.aravindan@gmail.com](mailto:nc.aravindan@gmail.com)
> RDKEMW-3268: Integrate Zram for RDK platforms to control swap feature

- recipes-extended/networkmgr-plugin/networkmanager-plugin_git.bb
Reason for change: changed network manager version 0.17.0
Risks: Medium
Priority: P0
> RDKEMW-3086 - Memory leak is observed with Network Manager plugin

- recipes-extended/cobalt/files/25/0001-Ensure-GCS-buckets-are-publicly-accessible-mirrors-5.patch
- recipes-extended/cobalt/files/25/0001-fix-for-build-failure-due-to-static-storage-URL-change.patch
- recipes-extended/cobalt/nplb_25.lts.stable.bb
Reason for change: Fix nplb build failure
Test procedure: Refer ticket
Risks: low
Priority: P2
Signed-off-by: Ansu Mathew <Ansu_Mathew@comcast.com>
> PREMIUMAPP-3308 : Add static storage URL changes

- recipes-extended/networkmgr-plugin/networkmanager-plugin_git.bb
Reason for change: Updated the Network Manager version to v0.17.0
Risks: Medium
Priority: P1
> RDKEMW-3914 - Integrate v0.17 of NetworkManager Plugin release to RDKE-8.1

- recipes-extended/networkmgr-plugin/networkmanager-plugin_git.bb
Reason for change: develop synup
Test Procedure: None
Risks: None
Signed-off-by: ramkumar_prabaharan [ramkumar_prabaharan@comcast.com](mailto:ramkumar_prabaharan@comcast.com)
> RDKEMW-2572 [RDKE] DeviceInfo.make coming as element for Sharp

- recipes-common/systimemgr/systimemgrfactory_git.bbappend
RDK-56904: meta-rdk-video adding pwrmgrplugin config
> RDK-56904: meta-rdk-video adding pwrmgrplugin config

- recipes-common/systimemgr/systimemgrfactory_git.bbappend
- recipes-extended/ctrlm/files/ctrlm-main.service
- recipes-extended/entservices/entservices-infra.bb
- recipes-extended/wpe-framework/wpeframework/wpeframework.service.in
- recipes-graphics/rtcore/rtcore_git.bb
Reverts rdkcentral/meta-rdk-video#373.  Pls don't rebase  with the develop with out ensuring the build
> Revert "Rebasing changes"

- recipes-extended/ctrlm/files/ctrlm-main.service
- recipes-extended/wpe-framework/wpeframework/wpeframework.service.in
> Rebase with Develop branch

- recipes-extended/sysint/sysint_git.bb
> RDKOSS-192: Sysint fix to revert the removed disk-check.service

- recipes-extended/sysint/sysint_git.bb
> Disk-Check Service for Video platforms 

- recipes-extended/sysint/sysint_git.bb
> Disk-Check Service for Video and TV platforms

- recipes-extended/rfc/rfc_git.bbappend
* Update rfc_git.bbappend
* Update rfc_git.bbappend
---------
> RDKE-791 - Generating minidump (#399)

- recipes-extended/wpe-framework/wpeframework/r4.4/Update-Trace-Level-Logging-Logic.patch
Update trace patch for nextline
> Update trace patch for nextline (#448)

- recipes-extended/entservices/entservices-deviceanddisplay.bb
- recipes-extended/entservices/entservices-infra.bb
- recipes-extended/wpe-framework/entservices-apis.bb
Reason for change : Updating entservices-apis tag
Test Procedure: Thunder RPC based testing of setVisible plugin method
Risks: Low
Priority: P1
Signed-off-by: Siva Thandayuthapani [sithanda@synamedia.com](mailto:sithanda@synamedia)
> RDKEMW-3813 - [AI2.0][RDKWindowManager] Add setVisible thunder interface

- recipes-extended/wpe-framework/wpeframework/r4.4/0001-SmarkLink-Crash-Fix.patch
- recipes-extended/wpe-framework/wpeframework_4.4.bb
* RDKEMW-4445: Sync changes RDKV[DELIA-66969] to RDKE
Reason for change: Bring-up changes of DELIA-66969 into RDKE.
Test Procedure: Build and validate crash
* Update wpeframework_4.4.bb
---------
> RDKEMW-4445: Sync changes RDKV[DELIA-66969] to RDKE (#461)

- recipes-extended/cobalt/libloader-app_24.lts.stable.bb
Reverts rdkcentral/meta-rdk-video#514
> RDKEMW-4615: Revert "RDKEMW-4615: RDK-E : libloader-app Remove AUTOINC from the PV"

- recipes-extended/cobalt/libloader-app_24.lts.stable.bb
- recipes-extended/networkmgr-plugin/networkmanager-plugin_git.bb
> Rebased develop

- recipes-extended/entservices/include/entservices-lisa-dac-config.inc
Reason for change: Update the config url for Lisa.
Test Procedure: Build and Verified.
Risks: None.
Signed-off-by: Sharnetha_SK@comcast.com
>  RDKEMW-4998:The DAC server URL to be updated (#595)

- recipes-extended/entservices/entservices-deviceanddisplay.bb
Reason for change: Replace the IARM Power Manager from Power Manager functionality. Test Procedure: Updated in the Jira RDKEMW-4603
Risks: Low
Signed-off-by:Ramesh Babu H bp-rbabu299@cable.comcast.com
> RDKEMW-4603: entservices dd Removal of CPC from system service

- recipes-extended/packager-lisa/packager-lisa_git.bb
Latest update to packagemanager is breaking rpi builds. This change fixes
> RDKEMW-5144: Fix compilation issues

- recipes-extended/entservices/entservices-deviceanddisplay.bb
* RDK-56578 : Updated srvrev for rdkservices-apis.
* Updated srcrev for entservices-apis and deviceanddisplay.
* Updated srcrev for deviceanddisplay and apis to release version.
---------
> RDK-56578 : Updated srvrev for rdkservices-apis. (#234)

- recipes-extended/entservices/entservices-deviceanddisplay.bb
Reason for change: develop synup
Test Procedure: verify build success and basic test
Risks: Low
Priority: P1
Signed-off-by: [ramkumar_prabaharan@comcast.com](mailto:ramkumar_prabaharan@comcast.com)
> RDKEMW-4719 Return an error message for firmware upto date validation

- recipes-extended/ctrlm/ctrlm-main.bb
Update recipe to remove RF4CE enable flag
> RDKEMW-3798: Update recipe to remove RF4CE enable

- recipes-extended/iarmmgrs/iarmmgrs_git.bb
Reason for change:Update  iarmmgrs_git bb file
Test Procedure: Build and test
> RDK-55763:Remove the unmapped binaries in rdkcore

- recipes-extended/entservices/entservices-infra.bb
- recipes-extended/wpe-framework/entservices-apis.bb
Reason for Change: Updated entservices-infra to 1.4.5
> RDK-57197 : Release of Privacy Plugin

- recipes-extended/entservices/entservices-mediaanddrm.bb
Reason for change: update retry mechanism
Risks: Low
Signed-off-by: vdinak240 <Vishnu_Dinakaran@comcast.com
> RDKEMW-5376 : VG not working after FSR

- recipes-extended/entservices/entservices-mediaanddrm.bb
* RDKEMW-5376 : VG not working after FSR
Reason for change: update retry mechanism
Risks: Low
Signed-off-by: vdinak240 <Vishnu_Dinakaran@comcast.com
* RDKEMW-5376 : VG not working after FSR
Reason for change: update retry mechanism
Risks: Low
Signed-off-by: vdinak240 <Vishnu_Dinakaran@comcast.com
---------
Signed-off-by: vdinak240 <Vishnu_Dinakaran@comcast.com
> RDKEMW-5376 : VG not working after FSR (#765)

- recipes-extended/entservices/include/entservices-lisa-dac-config.inc
1. Modify the dac configurations (template file) for RTK RDKE.
2. Corresponding DAC server updates in https://github.com/stagingrdkm/lgpub/pull/11/files
Test Procedure: Build verified
Risks: None.
Signed-off-by: antonyxavier_francis@comcast.com
> Unable to Validate DAC Apps : Failed to launch after install

- recipes-extended/ripple/ripple_git.bb
Added spec 1.3.0 to match ripple version 1.19.0
> RPPL-3236: Standard openrpc validator

- recipes-extended/networkmgr-plugin/networkmanager-plugin_git.bb
Reason for change: Upgrade to new release - 0.21.0 with following Bug fixes
- Fixed WiFi On/Off toggling failure
- Fixed the bug in IPAddress availability check upon wake-up
- Removed the SetPrimartInterface method
- Added input param validation for Ping and Stun methods
> RDKEMW-5550 - NetworkManager Plugin Release - 0.21.0

- recipes-extended/entservices/entservices-infra.bb
Reason for Change: Fix Auto mount issue with usb device
Test Procedure: Check for usb mount scenarios
Risks: Low
Priority: P1
> RDKEMW-4406 - Device failed to detect USB

- recipes-extended/entservices/entservices-inputoutput.bb
Reason for Change: Integrate the ODM Phase 2 to middleware
Test Procedure: Check AVOuput plugin APIs
Risks: Low
Priority: P1
> RDKEMW-5867 - Integrate the ODM Phase 2

- recipes-extended/entservices/entservices-inputoutput.bb
RDKEMW-6279: Revert of HdmiCecSink comrpc changes
Signed-off-by: yuvaramachandran_gurusamy <yuvaramachandran_gurusamy@comcast.com>
> RDKEMW-6279: Revert of HdmiCecSink comrpc changes

- recipes-extended/entservices/entservices-peripherals.bb
RDKEMW-5739: Update SRCREV for entservices-peripherals
Signed-off-by: yuvaramachandran_gurusamy [yuvaramachandran_gurusamy@comcast.com]
> RDKEMW-5739: Update SRCREV for entservices-peripherals

- recipes-extended/entservices/entservices-inputoutput.bb
RDKEMW-6230: update SRCREV for entservices-inputoutput
Signed-off-by: yuvaramachandran_gurusamy [yuvaramachandran_gurusamy@comcast.com]
> RDKEMW-6230: update SRCREV for entservices-inputoutput

- recipes-extended/entservices/entservices-infra.bb
- recipes-extended/wpe-framework/entservices-apis.bb
Reason for change: Interface header must follow the interface header RDKE coding guidelines
Test Procedure: please referred ticket descriptions Risks: Medium
Priority: P1
> RDKEMW-6226: Update the IMessageControl.h header file

- recipes-extended/entservices/entservices-mediaanddrm.bb
* RDKEMW-6466: Updated srcrev for mediaanddrm.
* Updated srcrev for mediaanddrm.
* Updated srcrev for mediaanddrm.
* Updated srcrev and version for mediaanddrm.
> RDKEMW-6466: Updated srcrev for mediaanddrm. (#1281)

- recipes-extended/entservices/entservices-casting.bb
- recipes-extended/entservices/entservices-connectivity.bb
- recipes-extended/entservices/entservices-deviceanddisplay.bb
- recipes-extended/entservices/entservices-infra.bb
- recipes-extended/entservices/entservices-inputoutput.bb
- recipes-extended/entservices/entservices-mediaanddrm.bb
- recipes-extended/entservices/entservices-peripherals.bb
- recipes-extended/iarmmgrs/iarmmgrs_git.bb
- recipes-extended/wpe-framework/entservices-apis.bb
- recipes-extended/wpe-framework/wpeframework-clientlibraries/r4.4/0001-PowerManagerClient-library-implementation.patch
- recipes-extended/wpe-framework/wpeframework-clientlibraries_4.4.bb
- recipes-extended/wpe-framework/wpeframework/wpeframework.service.in
Reason for change : component separation of player-interface from aamp
Test Steps : Basic Regression
Risk : Low
Signed-off : Naren Ramesh [naren_ramesh@comcast.com](mailto:naren_ramesh@comcast.com)
> RDKEMW-6895 : RDKE player-interface meta layer changes

- recipes-extended/wpe-framework/entservices-apis.bb
Changes ITextTrack::SendSessionData displayOffsetMs parameter from 32-bit to 64-bit
Change-Id: I109cd29b45fea42011858a8d0090b676aaa8bf86
> RDKEMW-6566: Update entservices-apis (#1329)

- recipes-extended/entservices/entservices-casting.bb
- recipes-extended/xdial/xdial.bb
* RDKEMW-5927: Update SRCREV in entservices-casting.bb
* RDKEMW-5927: Update SRCREV in xdial.bb
* RDKEMW-5927: Update SRCREV in entservices-casting.bb
* RDKEMW-5927: Use libsoup-2.4 insteadof libsoup3
---------
> RDKEMW-5927: Xcast crash fix during soup_uri_to_string API call (#1320)

- recipes-extended/entservices/entservices-peripherals.bb
RDKEMW-6998: Update SRCREV for entservices-peripherals.bb
Signed-off-by: yuvaramachandran_gurusamy <yuvaramachandran_gurusamy@comcast.com>
> RDKEMW-6998: Update SRCREV for entservices-peripherals.bb

- recipes-extended/iarmmgrs/iarmmgrs_git.bb
RDKEMW-6339: Added the distro check for supported Ports
Signed-off-by: yuvaramachandran_gurusamy <yuvaramachandran_gurusamy@comcast.com>
> RDKEMW-6339: Added the distro check for supported Ports

- recipes-extended/entservices/entservices-deviceanddisplay.bb
- recipes-extended/wpe-framework/entservices-apis.bb
- AckController refactored with WorkerPool
- Thread-safety fixes in ThermalController
- Improved deep sleep wakeup logic
- Robust client callback handling.
- Deepsleep timer wakeup
- Deepsleep user wakeup with multiple keys
- NetworkStandbyMode change via curl
- WakeupSrcMask change via curl
- Restart of tr69 / dsmgr
Risks: Low
> RDKEMW-6451: Improve robustness in PowerManager Plugin

- recipes-extended/entservices/entservices-deviceanddisplay.bb
- recipes-extended/wpe-framework/entservices-apis.bb
RDKEMW-6901:Update SRCREV in entservices-deviceanddisplay.bb 
Signed-off-by:Dineshkumar P [dinesh_kumar2@comcast.com]
> RDKEMW-6901:Update SRCREV in entservices-deviceanddisplay.bb

- recipes-extended/networkmgr-plugin/networkmanager-plugin_git.bb
RDKEMW-7118 - NetworkManager Plugin custom release - 0.20.1 
Reason for change: NetworkManager Plugin custom release - 0.20.1
> RDKEMW-7118 - NetworkManager Plugin custom release - 0.20.1

- recipes-extended/entservices/entservices-mediaanddrm.bb
Reason for change: disabled log containing text
Test Procedure: Same as ticket
Priority: P1
Risks: None
> RDKEMW-8319 : Sensitive Logs are Printed in TTS plugin

- recipes-extended/entservices/entservices-deviceanddisplay.bb
Reason for change: Updated the deviceanddisplay tag src revision
Signed-off-by:Dineshkumar P [dinesh_kumar2@comcast.com]
> RDKEMW-8332: Update the deviceanddisplay tag src revision

- recipes-extended/wpe-webkit/files/2.38.8/cmake-Fix-recompilation-on-rebuild-without-changes.patch
- recipes-extended/wpe-webkit/files/2.38.8/comcast-DELIA-68848-webrtc-improvements.patch
- recipes-extended/wpe-webkit/wpe-webkit_2.38.8.bb
- backport 'Fix recompilation on rebuild without changes'
- increase size of video appsrc buffer
- request key frame every 10 seconds
Reason for change: Luna gaming app
Test Procedure: See jira ticket
Risks: None
Signed-off-by: Eugene Mutavchi <Ievgen_Mutavchi@comcast.com>
Change-Id: Idd18d6bea4dfa3a356652af19b22f419d4c4152e
> RDKEMW-8618: WebRTC improvements

- recipes-extended/sysint/sysint_git.bb
Update sysint_git.bb to remove the service.
> RDKEMW-8748 Bring RDKTV-38567 changes to release/8.3.4.0
