recipes-extended/networkmgr-plugin/networkmanager-plugin_git.bb

RDK-56730: Unit test framework for routerDiscovery (#16)
* RDK-56730: Unit test framework for routerDiscovery
Reason for change: Integrate unit test framework
Test Procedure: Invoked unit test on every PR
* RDK-56730: Unit test framework for routerDiscovery
Reason for change: Integrate unit test framework
Test Procedure: Invoked unit test on every PR
---------

Rebase with Develop branch

---

recipes-extended/networkmgr-plugin/networkmanager-plugin_git.bb

* RDK-56730: Unit test framework for routerDiscovery
Reason for change: Integrate unit test framework
Test Procedure: Invoked unit test on every PR
* RDK-56730: Unit test framework for routerDiscovery
Reason for change: Integrate unit test framework
Test Procedure: Invoked unit test on every PR
---------

RDK-56730: Unit test framework for routerDiscovery (#16)

---

recipes-extended/wpe-framework/rdkservices-apis_1.0.bb

Reason for change: Bump rdkservices-apis to 1.3.0
Risk: Medium
Priority: P1
Change-Id: Icfe2f5fe253778ac045ad5346554143722ea4796

RDK-56155: Bump rdkservices-apis to 1.3.0

---

recipes-extended/networkmgr-plugin/networkmanager-plugin_git.bb

Reason for change: Updated the networkmanager plugin version to 0.13.0
Risks: low
Priority: P2

RDKEMW-2148 - GetIPSettings() method returns failure when ipversion is empty

---

recipes-extended/wpe-webkit/files/2.38.8/1423-revert.patch
recipes-extended/wpe-webkit/files/2.38.8/comcast-LLAMA-16805-Include-HW-secure-decrypt-decode-in-robu.patch
recipes-extended/wpe-webkit/wpe-webkit_2.38.8.bb

Reason for change: Revert for change brought in webkit downstream calling play() during a seek() is allowed by the spec. And the play event should be fired even if the seek hasn't completed. Test Procedure: Check ticket
Risks: NA

RDKEMW-3192 : Pandora does not resume playback

---

recipes-extended/thunderstartupservices/thunderstartupservices.bb

Reason for change: Moved the wpeframework-networkmanager.service to thunder-startup-services
Test Procedure: check the command "systemctl status NetworkManager"
Risks: Medium
Priority: P1
Signed-off-by: Gururaaja ESR<gururaja_erodesriranganramlingham@comcast.com>

RDKEMW-3311 - NetworkManager Thunder Plugin - Systemd Service cleanup

---

recipes-graphics/rdknativescript/rdknativescript_git.bb

Reason for change: Updated the recipe file of rdknativescript to include video.js rootfs
Test Procedure: build should be successful and video.js must be in rootfs
Risks: low
Priority: P2

RDKEMW-2170 : Merging recipe change for video.js

---

recipes-extended/entservices/entservices-deviceanddisplay.bb

Reason for the changes: Added hal lib dependency in the meta layer

RDK-57140: Adding the HAL support in Power Manager Plugin

---

recipes-extended/sysint/sysint_git.bb

Reason for change: Update sysint recipe to add required services
Test Procedure: Build RDKE image
Risks: Low
Signed-off-by: Aravindan NC [nc.aravindan@gmail.com](mailto:nc.aravindan@gmail.com)

RDKEMW-2321: Core files/minidump are not being generated for crashes

---

recipes-extended/networkmgr-plugin/networkmanager-plugin_git.bb

Reason for change: Upgrade to new release - 0.16.0 with following Bug fixes
* Fixed the deregistration of Security Agent upon one successful WPS Connect.
* JSONRPC response for Ping in the legacy plugin is addressed

RDKEMW-3914: NetworkManager Plugin Release - 0.16.0

---

recipes-extended/entservices/entservices-mediaanddrm.bb

Reason for change: Bring fix to R37
Risks: Low

RDKEMW-3169 : Fix VREX TTS2.0 VG not working in RDKE

---

recipes-extended/entservices/entservices-deviceanddisplay.bb

Reason for change: read make from MFR first and if not available fall back to device.properties.
Test Procedure: None
Risks: None
Signed-off-by: ramkumar_prabaharan ramkumar_prabaharan@comcast.com

RDKEMW-2572 [RDKE] DeviceInfo.make coming as element for Sharp

---

recipes-extended/ctrlm/files/ctrlm-main.service
recipes-extended/wpe-framework/wpeframework/wpeframework.service.in

Reason for change: wpeframework/ctrlm
should stop before secure folder to prevent
fs corruption and umount failure.
Test Procedure: Check system.log.
Risks: None

RDKEMW-4169 : /opt/secure unmounts early

---

recipes-extended/ctrlm/files/ctrlm-main.service
recipes-extended/wpe-framework/wpeframework/wpeframework.service.in

Reason for change: wpeframework/ctrlm
should stop before secure folder to prevent
fs corruption and umount failure.
Test Procedure: Check system.log.
Risks: None

RDKEMW-4169 : /opt/secure unmounts early (#348)

---

recipes-extended/entservices/entservices-infra.bb
recipes-extended/thunderstartupservices/thunderstartupservices.bb

Reason for change : Recipe changes for lifecyclemanager, storagemanager and appmanager
This includes changes for RDKEMW-2734, RDKEMW-2735, RDKEMW-2736 and RDKEMW-2737.
Test Procedure: Plugins are not activated by default. They are only activated when done manually. Risks: Medium
Priority: P1
Signed-off-by: Abhay Kant bp-akant305@cable.comcast.com

RDKEMW-2738 : Make recipe updates to build AppManager

---

recipes-extended/gstreamer-netflix-platform/rdk-gstreamer-utils.bb

RDKEMW-4105: RDK-E Update MW Manifests OSS Release 4.6.0 (#446)
RDK-E Update MW Manifests OSS Release 4.6.0
Realtek release 7.0.0 support with oss 4.6.0
Test Procedure: None
Risks: Low
Signed-off-by:Anooj Cheriyan <Anooj_Cheriyan@comcast.com>

Rebase with Develop

---

recipes-graphics/rdkshell/rdkshell_git.bb

**Reason for change:** As per analysis of this issue, the issue is reproduced only in the RDKE AML VA device builds; it is not observed in AML-VA RDKV builds. In RDKV build, in the soc specific meta layer named as meta-rdk-bsp-amlogic is have the bbappends for the rdkshell recipe file. https://code.rdkcentral.com/r/plugins/gitiles/collaboration/soc/amlogic/yocto_oe/layers/meta-rdk-bsp-amlogic/+/refs/heads/rdk-next/recipes-graphics/rdkshell/
In the lib32-rdkshell component source, the RDKSHELL_BUILD_FORCE_1080 OECMAKE flag is needed to enable, and this flag is used to enable the RDKSHELL_ENABLE_FORCE_1080 compilation CFLAG from the cmake file. Patches updates are missed in the RDKE build because patches are present in the vendor layer meta-rdk-bsp-amlogic. We enabled this needed OECMAKE …

RDKEMW-4393 : [AML-VA-DEVICES]Setting lower resolutions changes the screen size instead of screen quality.

---

recipes-extended/entservices/entservices-casting.bb
recipes-extended/entservices/entservices-deviceanddisplay.bb
recipes-extended/entservices/entservices-infra.bb
recipes-extended/entservices/entservices-inputoutput.bb
recipes-extended/entservices/entservices-peripherals.bb

Reason for Change: Fix wpeframework crash on reactivating plugin and power state change.
Reference:
- https://github.com/rdkcentral/entservices-casting/commit/13b65fbfdde52cf369258fe6ae7c62b9c9c3148d
- https://github.com/rdkcentral/entservices-deviceanddisplay/commit/393bc6f0eefe91d497737a092ee67fa0a2e56c5c
- https://github.com/rdkcentral/entservices-peripherals/commit/02fee0a5d6573921d8636ca269dc387f596d4666
- https://github.com/rdkcentral/entservices-inputoutput/commit/8aeb187ec11b99523b39dfcf329ddf2b10e72a3f
- https://github.com/rdkcentral/entservices-infra/commit/183ec6ac9a4492f12e2d6fce42878025ee5f9da9
Test Procedure: Please see ticket for details.

RDKEMW-4220: Fix wpeframework crash on reactivating plugin and power state change

---

recipes-extended/networkmgr-plugin/networkmanager-plugin_git.bb

Reason for change: Upgrade to new release - 0.19.0 with following Bug fixes
- Fixed Persistence related to interface enable/disable status
- Added addtional logs to understand WIFISignal monitoring thread

RDKEMW-4100 - NetworkManager Plugin Release - 0.19.0

---

recipes-extended/networkmgr-plugin/networkmanager-plugin_git.bb

This reverts commit 573994f7b78da2335cfe16b0a960e06d9ff5c767.

Revert "RDK7RM-50: Updating to tag 0.12.2 from support/rdk7-main"

---

recipes-graphics/uwebsockets/uwebsockets_git.bb

Reason for change: LibUV was not linked to uwebsocket
Test Procedure: build should be successful.
Risks: low
Priority: P2

    RDKEMW-3466 : Run Viper JSPP Integrated Player in RDK NativeScript

---

recipes-extended/wpe-framework/entservices-apis/RDKEMW-1007.patch

Reason for change: missing WAI support in RDK-E
Test Procedure: described in the ticket
Implements: code changes in AuthService and DeviceProvisioning
Risks: No
Source: COMCAST
License: Apache-2.0
Upstream-Status: Pending

RDKEMW-3788: Add WhoAmI support to DeviceProvisioning (meta-rdk-video)

---

recipes-extended/cobalt/larboard_revision.inc

Reason for change: Cobalt 25 maintenance
Test Procedure: N/A
Risks: None
Change-Id: I4ffd94c08fb58a9fbe496f2cc6221a99032d1856

RDKEMW-5327: Upgrade Cobalt 25 Larboard

---

recipes-extended/entservices/entservices-deviceanddisplay.bb
recipes-extended/wpe-framework/rdkservices-apis_1.0.bb

**Reason for change:** Update the SRC_REV for entservices-deviceanddisplay and entservices-apis component.
**Test Procedure:** Build and verify
**Risks:** High.
**Signed-off-by:** sundaramuneeswaran_muthuraj@comcast.com

RDK7RM-100: EntServices : DeviceInfo.modelid,make and socname APIs return ERROR_GENERAL response.

---

recipes-extended/networkmgr-plugin/networkmanager-plugin_git.bb

Reason for change: Upgrade to new release - 0.20.0 with following Bug fixes
- Fixed the bug in Resetting of Manual IPv4
- Fixed the SSID Name Length Check
- Added Connectivity Improvement
- Fixed the WiFi Signal Monitor thread exception
- Fixed documentation of GetSupportedSecurityModes
- Fixed the WiFi Migration settings

RDKEMW-2444 - NetworkManager Plugin Release - 0.20.0

---

recipes-extended/networkmgr-plugin/networkmanager-plugin_git.bb

Reason for change: Upgrade to new release - 0.20.0 with following Bug fixes
- Fixed the bug in Resetting of Manual IPv4
- Fixed the SSID Name Length Check
- Added Connectivity Improvement
- Fixed the WiFi Signal Monitor thread exception
- Fixed documentation of GetSupportedSecurityModes
- Fixed the WiFi Migration settings

RDKEMW-2444 - NetworkManager Plugin Release - 0.20.0 (#781)

---

recipes-extended/wpe-framework/wpeframework-clientlibraries/r4.4/0001-DELIA-64727-Prealloc-secure-memory-before-decrypt.patch
recipes-extended/wpe-framework/wpeframework-clientlibraries_4.4.bb

RDK-V stable2 contains newer changes
that are missing in RDK-E. This
change brings in the secure memory
pre-allocation feature
Test Procedure:
Verify encrypted playback on all
apps across all platforms.
Priority: P0
Risks: High
Change-Id: Ice4eb38108e0500dfb5913d52670d6bda42b71aa

RDKEMW-2303: Update gst-svp-ext version

---

recipes-extended/entservices/entservices-inputoutput.bb

JIRA ticket related to this changes is https://ccp.sys.comcast.net/browse/RDKEMW-5512
Test results can be found here: https://ccp.sys.comcast.net/browse/RDKEMW-5512?focusedId=22517278&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-22517278
Corresponding vendor changes were earlier merged and the details can be found here:
Tvsettings HAL
[RDKTV-33767: Remove ODM specific apis - phase2 by arjun-binu_comcast · Pull Request #17 · rdk-e/tvsettings-soc-amlogic](https://github.com/rdk-e/tvsettings-soc-amlogic/pull/17)
Meta PRs:
[RDKTV-33767: ODM specific apis removal in tvsettings-hal by arjun-binu_comcast · Pull Request #571 · rdk-e/meta-rdk-vendor-oem-sky-amlogic-common](https://github.com/rdk-e/meta-rdk-vendor-oem-sky-amlogic-common/pull/571)
[RDKTV-33767: ODM …

RDKEMW-5512: Implement a fix for the SaveTVDimmingMode failure

---

recipes-extended/entservices/entservices-inputoutput.bb

JIRA ticket related to this changes is https://ccp.sys.comcast.net/browse/RDKEMW-5510
Test results can be found here: 
https://ccp.sys.comcast.net/browse/RDKEMW-5510?focusedId=22569576&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-22569576
Corresponding vendor changes were earlier merged and the details can be found here:
Tvsettings HAL
[RDKTV-33767: Remove ODM specific apis - phase2 by arjun-binu_comcast · Pull Request #17 · rdk-e/tvsettings-soc-amlogic](https://github.com/rdk-e/tvsettings-soc-amlogic/pull/17)
Meta PRs:
[RDKTV-33767: ODM specific apis removal in tvsettings-hal by arjun-binu_comcast · Pull Request #571 · rdk-e/meta-rdk-vendor-oem-sky-amlogic-common](https://github.com/rdk-e/meta-rdk-vendor-oem-sky-amlogic-common/pull/571) …

RDKEMW-5510: Integrate the ODM Phase 2 middleware changes into RDKE

---

recipes-extended/wpe-framework/wpeframework/r4.4/Removed_Autostart_Check_From_WPEFramework.patch
recipes-extended/wpe-framework/wpeframework/wpeframework.service.in
recipes-extended/wpe-framework/wpeframework_4.4.bb

Reason for change: Removed the autostart options to helps to handle the plugin by the systemd during bootup
Test Procedure: please referred ticket descriptions
Risks: Medium
Priority: P1

RDKEMW-5890: Remove autostart check from WPEFramework code to be handled by systemd

---

recipes-extended/audiocapturemgr/audiocapturemgr_git.bb

Reason for change : With this change ACM will avoid descending into the test directory and will not generate these debugging
aids.
Test Procedure        : Analyze if binaries are removed from RDKE rootfs
Priority                    : P1
Risks                       : None
Signed-off-by        : daya_christudasan@comcast.com

RDK-55760: Analyze and remove Audiocapturemgr binaries

---

recipes-extended/entservices/entservices-deviceanddisplay.bb
recipes-extended/entservices/entservices-inputoutput.bb

Reason for change: pulled entservices-deviceanddisplay (3.1.1) and entservices-intputoutput(1.3.3)
Test Procedure: please referred ticket descriptions
Risks: Medium
Priority: P1

RDKEMW-3750 : Upgrade Thunder to Version R4.4.3

---

recipes-graphics/rdknativescript/rdknativescript_git.bb

Reason for change: copying modules to recipe-sysroot
Test Procedure: build should be successful.
Risks: low
Priority: P2

RDKEMW-5230: JSRuntimeLauncher component

---

recipes-extended/networkmgr-plugin/networkmanager-plugin_git.bb

Reason for change: Upgrade to new release - 0.23.0 with following Bug fixes
- Added L1/L2 workflow for LegacyNetwork, LegacyWiFi and NetworkManager Plugins
- Fixed RemoveKnownSSID method to handle the invalid inputs
- Fixed the logging in GetIPSettings

RDKEMW-6189,RDKEMW-6300,RDKEMW-6097,RDKEMW-5763,RDKEMW-5756 - NetworkManager Plugin Release - 0.23.0

---

recipes-extended/wpe-framework/wpeframework-clientlibraries/r4.4/0001-DELIA-64727-Prealloc-secure-memory-before-decrypt.patch
recipes-extended/wpe-framework/wpeframework-clientlibraries_4.4.bb

Reason for change: Latest version of gst-svp-ext provides a new API to pre-allocate secure memory.
Test Procedure: Verify encrypted playback across all apps on all platforms
Priority: P0
Risks: High

RDKEMW-2303, RDKEMW-5713: Update gst-svp-ext version

---

recipes-extended/wpe-framework/entservices-apis.bb

The next version of ITextTrack supports setting a session up to get its own CC data directly from the video decoder.
Change-Id: I2a4ebe51604384ce2e143e48b39a9811fbd238f9

RDKEMW-6446: Update ITextTrack interface to CC HAL (#1393)

---

recipes-extended/wpe-framework/wpeframework-clientlibraries/r4.4/0001-RDKEMW-7064-Dont-decrypt-fake-buffer-is-revoke-has-b.patch
recipes-extended/wpe-framework/wpeframework-clientlibraries_4.4.bb

Reason For Change:
Some platforms do not allow secure buffer allocations after Essos RM Revoke has been called, however, the pipeline may not have been shutdown yet and is still trying to decrypt data. We need to skip decryption in this case.
Priority: P2
Risks: Low
Test Procedure:
- Verify encrypted playback
- Verify Source switch during encrypted playback
- Verify app switch during encrypted playback
Change-Id: I59f16bd77bd0c476ac53d78998327188a7495568
DoD checklist: https://ccp.sys.comcast.net/browse/RDKEMW-7064?focusedId=22978717&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-22978717

RDKEMW-7064: Don't call decrypt for fake allocations

---

recipes-extended/entservices/entservices-infra.bb

Reason for change: OCDM Plugin Not Restarting After Crash
Test Procedure: Check weather after crash OCDM plugin should restart
Risks: Low
Signed-off-by:AkshayKumar_Gampa [AkshayKumar_Gampa@comcast.com](mailto:AkshayKumar_Gampa@comcast.com)

RDKEMW-7216: OCDM Plugin Not Restarting After Crash

---

recipes-extended/networkmgr-plugin/networkmanager-plugin_git.bb

Reason for change: Upgrade to new release - 0.25.0 with following Bug fixes
- Implemented SetHostname method which can send device's hostname over DHCP explicitly
- Implemented L1/L2 for netsrvmgr (RDK), libnm backends
- Clamped the WIFI Noise value to be within 0 dBm to -96 dBm
- Handled Plugin Termination sequence to stop the monitoring thread before exit
- Handled out-of-process plugin configuration as string
- Fixed Router Discovery to handle dual interface
- Fixed Internet Connectivity Monitoring to not to poll unless requested
- Addressed coverity reported issue

RDKEMW-6225 NetworkManager Plugin Release - 0.25.0

---

recipes-extended/networkmgr-plugin/networkmanager-plugin_git.bb
recipes-extended/wpe-framework/thunderhangrecovery/thunderHangRecovery.cpp
recipes-extended/wpe-framework/thunderhangrecovery/thunderHangRecovery.service

RDKEMW-7975 - Optimize the Internet Connectivity Monitoring approach port to support branch
Reason for change: Added device model and version details to the user agent of curl request and enabling the continuous monitoring only when the internet state is other fully connected
Test Procedure: check the tcpdump
RDKEMW-7974 - Improve thunder hang recovery process porting to support branch
Reason for change: Modified the thunder hang recovery with below 
- Only when the thunderHangRecovery is enabled, polling will be started for monitoring wpeframework otherwise no action will be taken 
- Create the json file to store the RFC value only when the RFC set is called when the device booted initially without any json file 
- Removed the old file and created new file to store the RFC value 
Test …

RDKEMW-7974, RDKEMW-7975 - Porting develop branch changes to support

---

recipes-extended/networkmgr-plugin/networkmanager-plugin_git.bb

Reason for change: Upgrade to new release - 1.3.0 with following Bug fixes
- Implemented NetworkManagerProxy library which can help Thunder to Create COM-RPC connection to Out-Of-Process plugin
- Implemented Internet Connectivity Monitoring for specific to Primary Interface.
- Updated to not to post onInternetStatusChanged event when secondary interface is disturbed.

RDKEMW-8302 - NetworkManager Plugin Release - 1.3.0

---

recipes-extended/networkmgr-plugin/networkmanager-plugin_git.bb

Reason for change: Upgrade to new release - 1.4.0 with following Bug fixes
- Implemented logic to not to persist SSID when asked
- Implemented IP Address caching to avoid making RPC request to networkmanager when interface status not changed.
- Fixed the Router Discovery app crash when AP does not support UPNP

RDKEMW-7523 - NetworkManager Plugin Release - 1.4.0

---

recipes-extended/wpe-framework/wpeframework/r4.4/Revert_PR-665_support_JSON_Parsing.patch
recipes-extended/wpe-framework/wpeframework_4.4.bb

Reason for Change:Validated the Thunder R4.4.3 + RDK patch using the BigJSONTest Test Plugin. The TestConsumer receives only the first three events. The fourth event is not notified to the consumer—it gets stuck at the Thunder layer. The fifth event is received by the Thunder layer but gets mixed up with the pending fourth message, causing deserialization errors due to the combined data from both messages. After this point, no further events are received or notified, and the Thunder layer enters a bad state. I suspected the Metro changes introduced in PR #1625. After reverting those changes and revalidating, the issue was resolved
Test Procedure:Please refer to the ticket description. 
Risks: Medium
Priority: P1

RDKEMW-8985: JSON Parsing Failure for Long Strings Containing "\\"
